### PR TITLE
feat: luarocks/rocks.nvim support

### LINKED ISSUE #18: Package for LuaRocks
Hi, 

Would you consider packaging this nvim plugin to [LuaRocks](https://luarocks.org/) so that the package manager [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim) can detect it?
The `rocks.nvim` team [prepared a github action](https://github.com/nvim-neorocks/luarocks-tag-release) that automates this process.

### PR DESCRIPTION
**Pull request by mrcjkb**
Hey :wave: 

### Summary

This PR is part of a push to get neovim plugins on [luarocks.org](https://luarocks.org/labels/neovim).

See also:

- [rocks.nvim](https://github.com/nvim-neorocks/rocks.nvim), a new luarocks-based plugin manager.
- [this blog post](https://mrcjkb.github.io/posts/2023-01-10-luarocks-tag-release.html).

With luarocks/rocks.nvim, it is [the plugin authors' responsibility to declare dependencies - not the user's](https://github.com/nvim-neorocks/rocks.nvim?tab=readme-ov-file#grey_question-why-rocksnvim).
Installing this plugin becomes as simple as `:Rocks install telescope-zf-native.nvim`.

### Things done:

- Add a workflow that publishes tags to luarocks.org when a tag or release is pushed.
- Add a release-please workflow that creates release PRs with SemVer versioning based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

The workflows are based on [this guide](https://github.com/nvim-neorocks/sample-luarocks-plugin)

### Notes:

> [!IMPORTANT]
> 
> - **For the luarocks workflow to work, someone with a luarocks.org account will have to add their [API key](https://luarocks.org/settings/api-keys) to this repo's [GitHub actions secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets#creating-encrypted-secrets-for-a-repository)**.

- On each merge to `master` (if this lands on `master`), the `release-please` workflow creates (or updates an existing) release PR.
- You decide when to merge release PRs.
  Doing so will result in a SemVer tag, a changelog update, and a GitHub release, which will trigger the `luarocks` workflow.
  If you would like versioning to start from a specific version (e.g. 2.0.0), you can [configure this with a manifest](https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md).
- Tagged releases are installed locally and then published to luarocks.org.
  - If you push tags from a local checkout, the workflow is triggered automatically.
  - If you use GitHub releases to create tags, you may need to [add a PA token](https://github.com/nvim-neorocks/sample-luarocks-plugin?tab=readme-ov-file#generating-a-pat-personal-access-token) for the workflow to be triggered automatically.
- Due to a shortcoming in luarocks.org (https://github.com/luarocks/luarocks-site/issues/188), the `neovim` and/or `vim` labels have to be added  to the luarocks package manually (after the first upload), for this plugin to show up in https://luarocks.org/labels/neovim or https://luarocks.org/labels/vim, respectively.

### CODE REVIEW

**Review by NTBBloodbath — APPROVED** [review]

**Comment by natecraddock** [comment]
Sorry for the delay on this, I've been swamped the last month. I'll take a closer look later today / over the next few days and get back to you

**Comment by natecraddock** [comment]
Hey @NTBBloodbath, since you are [part of neorocks](https://github.com/natecraddock/telescope-zf-native.nvim/issues/18#issuecomment-2103237739), I'll let you handle this one :) Looks like you approved it. Feel free to merge whenever you feel it is ready

**Comment by NTBBloodbath** [comment]
> Hey @NTBBloodbath, since you are [part of neorocks](https://github.com/natecraddock/telescope-zf-native.nvim/issues/18#issuecomment-2103237739), I'll let you handle this one :) Looks like you approved it. Feel free to merge whenever you feel it is ready

Hey, sorry it took so long. It seems like I would need to add both my GitHub token for CI actions and my luarocks API key as well in the repository but as a contributor I don't seem to be able to.

Not sure if you could create them in your GitHub account, otherwise feel free to slap me with an email and I'll reply back with the required keys to get this to work properly

**Comment by NTBBloodbath** [comment]
> > Hey @NTBBloodbath, since you are [part of neorocks](https://github.com/natecraddock/telescope-zf-native.nvim/issues/18#issuecomment-2103237739), I'll let you handle this one :) Looks like you approved it. Feel free to merge whenever you feel it is ready
> 
> Hey, sorry it took so long. It seems like I would need to add both my GitHub token for CI actions (it is completely safe, only read permissions and CI ones) and my luarocks API key as well in the repository but as a contributor I don't seem to be able to.
> 
> Not sure if you could create them in your GitHub account, otherwise feel free to slap me with an email and I'll reply back with the required keys to get this to work properly

**Comment by natecraddock** [comment]
@NTBBloodbath so there is more work to do than just merge this? Like I wouldn't be able to merge it myself and everything just work?

If I understand right, I would need to add an environment to this repository with your luarocks API key? Feel free to email me any information I need to set this up. Either my git email or the one on my website are fine

**Comment by NTBBloodbath** [comment]
> @NTBBloodbath so there is more work to do than just merge this? Like I wouldn't be able to merge it myself and everything just work?
> 
> If I understand right, I would need to add an environment to this repository with your luarocks API key? Feel free to email me any information I need to set this up. Either my git email or the one on my website are fine

Yes sir, there are two secrets that must be added to the repository!

1. the luarocks CI needs a luarocks API key in order to be able to publish the plugin to the luarocks server (must be called `LUAROCKS_API_KEY`).
2. the `release-please` CI action for semver releases requires a GitHub token with read-only permissions with only write permissions for CI stuff according to the documentation (must be called `PAT`).

It's already a little late here, so I'll get them to you early tomorrow if that's okay 🙂

**Pull request merged**
